### ISSUE TITLE
Pipx Uninstall Instruction Incorrect

### ISSUE THREAD

**Issue by gloc-mike** [dhruvkb/pls#13]
Hi,

Really minor issue regarding the instructions for uninstalling from pipx in [getting started](https://dhruvkb.github.io/pls/get_started.html#installing-1).

Instructions show `pipx uninstall peotry` instead of `pls`.

![Screen Shot 2022-03-06 at 3 48 24 pm](https://user-images.githubusercontent.com/2324626/156909741-e29b3c6f-385c-44c1-bbf6-25d76258f512.png)

Really enjoying `pls`! Great job!

BTW Found out about `pls` via the Python Bytes podcast (episode [272](https://pythonbytes.fm/episodes/show/272/the-tools-episode)) -  also broadcast on [YT](https://youtu.be/8HKliSbA-gQ?t=501).

Thanks
Michael

**Comment by dhruvkb** [comment]
Thanks @gloc-mike for reporting this (and giving `pls` a try), I was "referencing" Poetry docs when I wrote this 😆 .
