### ISSUE TITLE
Coloring of date fields inconsistent

### ISSUE THREAD

**Issue by dzerrenner** [dhruvkb/pls#14]
## Description
When using `pls` in table ode, any fields containg a date are highlighted somewhat strange. The color of the year and seconds are not the same as the other components.

## Reproduction
1. `pls -a -d ctime`
2. See error.

## Expectation
The whole date field has the same color.

## Screenshots
![pls_date](https://user-images.githubusercontent.com/260689/158159953-433bc749-ef79-4148-98ba-1a61a39a7a3d.png)

## Environment
 - Device: cloud ecs
 - OS: arch linux
 - Shell: zsh

## Additional context
I suspect `rich` for the output formatting lapse. But I can't reproduce this with `rich`:
```python
import rich
rich.print("2022-03-01 10:00:00") 
```
gives me the date and the time in one color for the time and date respectively.
Maybe add `markup=False` on the ourput for date colums?

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dzerrenner** [comment]
The docs state that the output can modified with rich markup. This is a valid workaround: add `-t '[grey]%Y-%m-%d %H:%M:%S[/]'` In hindsight, the dim year and seconds could also be a readability hint. If this is the case, consider the issue as nonexistant 😄

**Comment by dhruvkb** [comment]
@dzerrenner that was actually intentional as those are the two less important parts of the date, but I can see how that's confusing and looks like a bug in the absence of documentation. I suppose a better way would be to not format the date by default and let users pick their preferred format via the CLI arg.

**Comment by dzerrenner** [comment]
Yeah, this is actually documented quite well, i just didn't read the right chapter... Never mind, I'll close the issue. 👍
