### ISSUE TITLE
Broken link in `README`

### ISSUE THREAD

**Issue by spietras** [dhruvkb/pls#2]
Cool software! Just one simple thing I've noticed while browsing the `README`: the link to "customization" README points to nothing. Probably should be https://github.com/dhruvkb/pls/blob/main/src/pls/data/README.md (notice the `src`) instead of https://github.com/dhruvkb/pls/blob/main/pls/data/README.md.

**Comment by dhruvkb** [comment]
Yes, @spietras the project underwent quite a major reorganisation in 7e40ded which must have broken the link. Would you like to open a PR to fix this?

**Comment by spietras** [comment]
Sure, there you go: #4
