### ISSUE TITLE
List contents of multiple directories in one command

### ISSUE THREAD

**Issue by arjan-s** [dhruvkb/pls#28]
## Description

`pls *` or `pls <dir1> <dir2>` currently shows the help and an error. It would be great if `pls` could show the contents of multiple directories in one command like `ls` can.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
@arjan-s I've started working on this and it's coming soon. It's a pretty big change because the code was tightly written considering a single directory as the working directory, especially with all the `.pls.yml` config cascading logic.

**Comment by dhruvkb** [comment]
I've just deployed [v5.0.0](https://pypi.org/project/pls/5.0.0/) to PyPI which adds support for multiple positional arguments.

<img width="411" alt="Screenshot 2022-05-23 at 9 06 20 PM" src="https://user-images.githubusercontent.com/16580576/169871740-856de149-12c8-48a3-b318-558e4fa90bea.png">

Please upgrade to make use of this feature.

**Comment by arjan-s** [comment]
That's awesome! Thank you!
