### ISSUE TITLE
Support for alternative user-level config file location

### ISSUE THREAD

**Issue by acbuie** [dhruvkb/pls#32]
## Problem
Many command line tools have user-level configs in the home directory, but offer ways to de-clutter that directory by setting custom environmental variables. `pls` could support this idea fairly simply (I think?).

## Description
`pls` could read an environmental variable called `PLS_USER_CONFIG_DIR` (or something like that) when constructing the `conf_paths` list in `config/files.py`. 

There is already at least one environmental variable used by `pls`, so I don't think it would be too odd to support another one.

## Implementation
I admit, I'm not too familiar with the architecture of `pls`, but a quick look through `config/files.py` and `globals/state.py` makes me think implementing this wouldn't be too difficult. 

Adding a function `get_user_conf()` before `get_home_conf()` in `find_configs()` could work. Something along the lines of:
```
def get_user_conf():
    user_conf_dir = os.getenv("PLS_USER_CONFIG_DIR")

    if user_conf_dir is None:
        return None

    test_path = user_conf_dir.joinpath(conf_name)
    return test_path if _is_valid(test_path) else None
```
This could be inserted into `find_configs()`:
```
def find_configs():
...
    if ancestor_confs := get_ancestor_confs(curr_dir):
        conf_paths.extend(ancestor_confs)
    if user_conf := get_user_conf():
        conf_paths.append(user_conf)
    if (home_conf := get_home_conf()) and home_conf not in conf_paths:
        conf_paths.append(home_conf)
...
```
- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
`pls` actually uses several environment variables:

- `PLS_MAX_HEIGHT` sets how many directories to go up to look for cascading config files
- `PLS_LOG_LEVEL` is helpful to see logs during development
- `PLS_NO_UPDATE_CHECK` prevents the network call for checking if there are any new versions

So adding another one should not be a problem. But the growing number of these variables means that there needs to be proper documentation for them in the [docs](https://dhruvkb.github.io/pls).
