### ISSUE TITLE
Support generic folder/directory color and icon changes

### ISSUE THREAD

**Issue by acbuie** [dhruvkb/pls#33]
## Problem
Forgive me for opening another issue so quickly! This is an excellent application, and I've been enjoying using it. I can't seem to find documentation about how to change the default directory icon or color. 

I have tried an `extension` node with an empty string, and a `pattern` node which looks for `\` or `/` at the end of the name. Neither have worked, and without any examples in the documentation, I'm assuming this idea is not supported at the moment. 

## Description
It would be very nice to be able to specify directories either by `pattern` or `extension`, or some other mechanism within `.pls.yml`. This would allow the user to change the default directory color or icon. 

## Alternatives
What I am trying to do is match the color output of `pls` to the color output of `ls`, which uses the LS_COLORS environmental variable. `pls` could make the default output colors use this variable, but it is not always set for users. On macOS, it is only used if the users use the GNU-based `ls`, for example. I think a simpler solution would be to make it easier to change directory colors, and allow the user to input any other extensions or patterns they want. That part is already very simple thanks to the excellent config!

## Additional context
My apologies if this is already supported! I looked long and hard through the documentation but failed to find the solution to this.

## Implementation
- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I'll get back to this issue soon with a comprehensive solution but at the moment you can change the folder icon by setting the `"folder"` icon to your preferred glyph inside the `nerd_icons` or `emoji_icons` config.

**Comment by dhruvkb** [comment]
> Forgive me for opening another issue so quickly! This is an excellent application, and I've been enjoying using it.

I really appreciate you for taking the time, and opening these well documented issues. You're helping make `pls` better for everyone! 😄

**Comment by acbuie** [comment]
Thanks for your thoughts! Allowing the users to access the supported nodes would make the configuration much more flexible. I think somebody wanting to change directory or symlink colors and icons would be a reasonably common use case for the application to support.

**Comment by dhruvkb** [comment]
Sorry for the lack of activity on the issue for nearly two weeks. I've added a way for this to be defined in the newest minor (feature) release v5.3.0. This approach uses `constants` which are a huge collection of constants that you can simply overwrite.

An example can be found in the [project's `.pls.yml` file](https://github.com/dhruvkb/pls/blob/23601bc2e2674c109b0cfc5eaa4806d8035a5f5c/.pls.yml#L20). You can also refer to the [huge list of modifiable constants](https://github.com/dhruvkb/pls/blob/23601bc2e2674c109b0cfc5eaa4806d8035a5f5c/src/pls/data/constants.yml) for ideas.
