### ISSUE TITLE
Folder icons render as ? symbols.

### ISSUE THREAD

**Issue by srihari9n** [dhruvkb/pls#38]
## Description
All the folders have ? icon (attached screenshot) , is this the default icon? Am I missing something? 

## Reproduction

1. pip install pls
2. type in `pls`
3. See the icons.

## Expectation
Folders should have a icon based on name (for common folders) or have just a folder icon, but seeing question mark.

## Screenshots
<img width="233" alt="image" src="https://user-images.githubusercontent.com/101564310/182763684-45d4af78-abb4-4647-b525-012cd5a315de.png">

## Environment

 - Device: Macbook Pro m1
 - OS: MacOs Monterey (12.5)
 - Version: 5.3.0

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@srihari9n it seems that you do not have a Nerd Font installed. To see the icons, you need to install [one of these fonts (whichever you prefer)](https://www.nerdfonts.com/font-downloads) and set it as your terminal font.

**Comment by srihari9n** [comment]
I was sure that I had one installed since I use oh-my-posh installed and that works okay, but I will still try installing one and get back to you.

**Comment by srihari9n** [comment]
@dhruvkb Yes, turns out, I had a couple of them installed but I have not set my terminal font to it. Works okay now. Thanks.

You can close this issue.
