### ISSUE TITLE
Note pipx installation method in documentation

### ISSUE THREAD

**Issue by treyhunner** [dhruvkb/pls#7]
I usually use pipx to install command-line utilities that happen to be written in Python but are meant to be installed globally.

pls installs well with pipx and I'd recommend noting this in the installation instructions.

[rich-cli](https://github.com/Textualize/rich-cli#installation), [poetry](https://python-poetry.org/docs/#installing-with-pipx), [nox](https://nox.thea.codes/en/stable/tutorial.html#installation), and [pyxtermjs](https://github.com/cs01/pyxtermjs#installation) all mention pipx installation instructions in their documentation for example.

**Comment by dhruvkb** [comment]
Thanks @treyhunner! Updated the docs to include `pipx` in 6940317. Updated docs will be live shortly.
