### ISSUE TITLE
Make upgrade nag configurable

### ISSUE THREAD

**Issue by MichaelXavier** [dhruvkb/pls#79]
## Problem
Currently when a new version of pls comes out, it seems that every time the user uses the tool it appends to the output that there is an upgrade. It seems like it might even make an HTTP request every time? I would suggest that this feature should at least be toggleable at the config level and documented. I would go further and argue that this should probably be avoided altogether or defaulted to off.

## Description
This can be problematic if you're using it for scripts and can be quite annoying to the user, especially if they install through their package manager and just have to wait for the update to become available. It also seems inappropriate that a relatively low level command would insist so heavily in upgrades or make an HTTP call on every use.

**Comment by dhruvkb** [comment]
I completely agree @MichaelXavier.

Some context: v6.0.0 is the last Python release and the project has been [rewritten in Rust](https://github.com/dhruvkb/pls/discussions/78). The upcoming new release will not have update checking at all, relying on the distribution mechanism (`brew`/`apt` etc.) to handle updates.

That said, as of v6.0.0 the update check should only happen when printing the version `pls --version` and setting the env var `PLS_NO_UPDATE_CHECK` should stop `pls` from checking for updates.

**Comment by MichaelXavier** [comment]
Thanks @dhruvkb. I use NixOS/Nixpkgs so in order to try out 6.0.0 I'd need to write a local patch for the existing `pls`. I figured if I was going to go through that trouble I might as well just create a nix derivation for the rust version so that's what I did. There were some slight CLI changes but I've adjusted my shell aliases to those. Thanks, and thanks for pls!

**Comment by dhruvkb** [comment]
@MichaelXavier the `PLS_NO_UPDATE_CHECK` works even before v6.
